version: '3.8'

services:
  api:
    container_name: odary-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=odary_dev;Username=postgres;Password=postgres;Port=5432
      - ConnectionStrings__Redis=redis:6379
      - JwtSettings__SecretKey=your-super-secret-key-that-should-be-at-least-32-characters-long-for-security
      - JwtSettings__Issuer=Odary.Api
      - JwtSettings__Audience=Odary.Api.Users
      - JwtSettings__ExpiryHours=1
      - JwtSettings__RefreshTokenExpiryDays=7
      - EmailSettings__SmtpHost=mailhog
      - EmailSettings__SmtpPort=1025
      - EmailSettings__FromEmail=noreply@odary.com
      - EmailSettings__FromName=Odary Dental Practice
      - EmailSettings__FrontendUrl=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./src/Odary.Api:/app/src
    networks:
      - odary-network

  postgres:
    container_name: odary-postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=odary_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - odary-network

  redis:
    container_name: odary-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - odary-network

  mailhog:
    container_name: odary-mailhog
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    environment:
      - MH_STORAGE=memory
    networks:
      - odary-network

volumes:
  postgres_data:
  redis_data:

networks:
  odary-network:
    driver: bridge 